# Generated by Django 4.2.13 on 2024-05-15 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='clean-work')),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('hours', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo-gallery')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photogallery', to='clean.service')),
            ],
            options={
                'verbose_name': 'PhotoGallery',
                'verbose_name_plural': 'PhotoGallerys',
            },
        ),
    ]
